name: Update locales

on:
  push:
    # run this workflow when someone pushes to the l10n_main branch
    # TODO remove other branches after testing
    branches: [ l10n_main, main, WIP-2706-update-locales ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Create the mock file for the update_locales command to work, otherwise
    # we'll get an 'no such file' error
    - name: Create mock .env file
      run: echo "DEBUG=true" > .env

    - name: Run update_locales command
      run: ./bw-dev update_locales

    - name: Create pull request
      run: |
        git commit -a -m
        gh pr create -B main -H l10n_main --title 'Merge l10n_main into main' --body 'Created by Github action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
